@startuml

class 用户{
    用户编号
    姓名
    github账号
    github账号修改日期
    密码
    用户状态
}
class 管理员{
    管理员编号
    所属部门
}
class 学生{
    学号
    班级
    网站正确与否汇总
}
class 教师{
    教师工号
    教师所属部门
}
class 学期{
     学期编号
}
class 课程{
    课程编号
    课程名称

}
class 教师选课{
    教师工号
    课程编号
    学期编号
    课程名称
}
class 学生选课{
    学号
    教师工号
    课程编号
    学期编号
}
class 实验{
    实验编号
    课程编号
    学期编号
    实验名称
    评分项数量
    评分项[评分项数量]
}
class 学生实验成绩{
    学号
    课程编号
    实验编号
    实验分数
    评分项得分[评分项数量]
    评分项描述[评分项数量]
    评改日期
}
class 学生课程成绩{

    学号
    课程编号
    学期编号
    分数
}

用户 <|-- 教师
用户 <|-- 学生
用户 <|-- 管理员
教师 "1" -- "n"教师选课
学生 "1" -- "n"学生选课
学生选课 "n"--"1" 教师选课
学生选课 "1"--"1" 学生课程成绩
教师选课 "n" --"1" 课程
学期 "1"--"n"教师选课
教师选课 "1"--"*"实验 :布置
学生选课 "1"--"n" 学生实验成绩
@enduml